Add instructions for building a custom collector
elastic/opentelemetry pull request #6
Opened 2024-08-14 20:11 UTC by mdbirnstiehl

This PR closes [Issue 4126](https://github.com/elastic/observability-docs/issues/4126) and adds steps for building a custom collector.

Things to figure out:

- [ ] Can we use the same config for MacOS and Linux
- [ ] Complete K8s steps

2024-08-21 07:18 UTC, mlunadia requested changes
We should not provide users instructions to build a collector per platform but instructions to build a collector that has all the EDOT components and then provide them with options to configure it for different use cases.

2024-08-21 13:16 UTC, mdbirnstiehl commented on docs/configure-upstream-collector.md
> +## Build a custom collector for MacOS or Linux
I structured it in this way according to @ChrsMark comment [here](https://github.com/elastic/observability-docs/issues/4126#issuecomment-2275333268). Perhaps @ChrsMark and @ishleenk17 can provide feedback on this PR on how to provide this info with all of the options?

2024-08-27 15:08 UTC, mlunadia commented on docs/configure-upstream-collector.md
> +## Build a custom collector for MacOS or Linux
@AlexanderWert can you confirm this one? AFAIK is a single binary with different configs, not a binary per platform.

2024-08-27 15:40 UTC, AlexanderWert commented on docs/configure-upstream-collector.md
> +## Build a custom collector for MacOS or Linux
The builder itself has different binaries for different platforms, see here: https://opentelemetry.io/docs/collector/custom-collector/#step-1---install-the-builder

But the rest of the building instructions should be identical.

2024-08-27 15:44 UTC, mlunadia commented on docs/configure-upstream-collector.md
> +## Build a custom collector for MacOS or Linux
ah makes sense.
@mdbirnstiehl so what you have now makes sense but I feel is off to have a different flow for each platform ideally we want to have a single flow with different options as per the link shared above.

2024-08-27 16:02 UTC, mdbirnstiehl commented on docs/configure-upstream-collector.md
> +## Build a custom collector for MacOS or Linux
@mlunadia Got it, I'll update to one flow.

2024-08-28 19:32 UTC, mdbirnstiehl commented on docs/configure-upstream-collector.md
> +## Build a custom collector for MacOS or Linux
@mlunadia @AlexanderWert I've update the doc to follow a single flow. I'm wondering if the info on the OpenTelemetry Collector Contrib distribution should still be on this page or if it makes sense to move that to its own page. Do we need to add specific steps on updating the collector contrib?

2024-08-31 07:39 UTC, mlunadia approved these changes
LGTM

2024-08-31 07:40 UTC, merged